### ISSUE TITLE
The homepage is not working

### ISSUE THREAD

**Issue by yuankailiu** [milgra/airpodssoundqualityfixer#10]
Hi, looks like the link of the homepage for downloading is not working:
[http://milgra.com/airpods-sound-quality-fixer.html](http://milgra.com/airpods-sound-quality-fixer.html)

Is this an easy fix? Thanks!

**Comment by milgra** [comment]
Hi, yes, I moved on with my homepage and unfortunately I'm not a mac user any more, my certificates wouldn't work so you have to compile it for yourself it you would like to make it work :(

**Comment by yuankailiu** [comment]
I see. I would love to try to compile it, but I don't know how to do it on my mac. Do you have a guide for that? Thanks!

**Comment by eugeneteoh** [comment]
Hi there, thanks for this. Can you update the readme on how to compile the code? I'm not familiar with objective c.

**Comment by stormychel** [comment]
> Hi there, thanks for this. Can you update the readme on how to compile the code? I'm not familiar with objective c.

- install Xcode
- start Xcode
- clone repo from here, pick "open with Xcode" (see attached screenshot 1)
- try building (Product->Build)
- fix errors (probably only the signing issue mentioned by @milgra
- archive app (Product->Archive)
- when archived, click Distribute
- pick Copy App (see attached screenshot 2)
- press Next, pick a location (Applications?)
- enjoy this lovely app

<img width="715" alt="Screenshot 2022-02-13 at 08 23 37" src="https://user-images.githubusercontent.com/3184001/153743474-80439365-063b-4ac4-bcf2-514d5bed2c08.png">

<img width="731" alt="Screenshot 2022-02-13 at 08 27 14" src="https://user-images.githubusercontent.com/3184001/153743480-9e4d136c-5f93-48a2-803e-8c1242b4234c.png">

**Comment by milgra** [comment]
Hi thank you for the questions and answers. The last version is still downloadable from [releases](https://github.com/milgra/airpodssoundqualityfixer/releases/tag/1.0) , altough I don't know if MacOS allows it to be installed, probably a fresh build is the best.
