### ISSUE TITLE
Can't donate because it is PayPal only. Crypto options?

### ISSUE THREAD

**Issue by stormychel** [milgra/airpodssoundqualityfixer#11]
Some of us can't donate because of not having a PayPal account.

Can we donate to a Bitcoin or other Crypto wallet instead?

Other options for those not owning Crypto?

Thanks :)

**Comment by milgra** [comment]
Hi, thanks for the question but I'm not maintaining it any more :( but if you really want to donate my bitcoin address is 37cSZoyQckihNvy939AgwBNCiutUVN82du
 , thank you!
