### ISSUE TITLE
This script is no longer compatible with macOS Ventura. 

### ISSUE THREAD

**Issue by anuragrao04** [milgra/airpodssoundqualityfixer#16]
The app runs without any apparent error message but there is no icon on the menu bar and the enforcement of default audio does not happen.

**Comment by stormychel** [comment]
Hello @anuragrao04 which version did you try? This works on Ventura without any problems.
You might want to try this release:
https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer/releases/tag/v1.0.2

**Comment by anuragrao04** [comment]
I'm sorry, I meant macOS Ventura. I will try the release you sent to me and revert back. I'm extremely sorry for the confusion

**Comment by anuragrao04** [comment]
Thanks! that worked. The only bug is that I sometimes have to reselect which input to force randomly. This issue is very rare though. I will open a new issue on your fork @stormychel if this issue arises more frequently

**Comment by stormychel** [comment]
No worries 😊 I hope my release works for you!
