### ISSUE TITLE
Missing release of latest pull request

### ISSUE THREAD

**Issue by mikigal** [milgra/airpodssoundqualityfixer#8]
Hi,
there's no binary release of pull request that I made (it keeps selected device after app reset) - https://github.com/milgra/airpodssoundqualityfixer/commit/0981551f851d091c3c6f1753d510e32e8d30af2c

Can you add it?

**Comment by milgra** [comment]
Hi, I no longer maintain this app since I switched from apple, feel free to fork is and create a release, I will add you to the top of the readme.
